apiVersion: v1 
kind: ReplicaSet 
metadata:
  name: roboshop
  labels:
    purpose: replica-demo
spec:
 replicas: 2
 selectors:
   matchLebels:
     purpose: nginx-demo
 templates:
   metadata:
     labels:
       purpose: nginx-demo
   spec:
    containers:
     - name: nginx
       image: nginx